typography_spectrum: 0.3235792040359229
color:
  brandColors:
    - '#0d0d0d'
    - '#777c80'
    - '#d0cdc6'
    - '#505050'
    - '#fc0000'
  brandStrength: 0
  lightness: 0.5154371275566518
  saturation: 0.6454868146684021
  rhythmicContrast: 0.9503300995565951
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: ExpertCarAudio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Expert Car Audio
description: Where only the very best will do
purpose: []
